version: '3'

services:
  files:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes: ["./files:/opt/files"]
    environment:
      PORT: "5000"
      FLASK_DEBUG: "true"
    ports:
      - "5000:5000"