name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/render-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.RENDER_API_KEY}}
          heroku_app_name: "serverlabs"
          heroku_email: "vovkayakimenko2564@gmail.com"
          usedocker: true