name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bounceapp/render-action@0.6.0
        with:
          api_key: ${{secrets.RENDER_API_KEY}}
          app_name: "serverlabs"
          email: "vovkayakimenko2564@gmail.com"
          usedocker: true